# Generated by Django 5.2.6 on 2025-09-16 19:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DjangoCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ]
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "city",
                "verbose_name_plural": "cities",
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="DjangoWeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("precipitation", models.FloatField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_data",
                        to="core.djangocity",
                    ),
                ),
            ],
            options={
                "verbose_name": "weather data",
                "verbose_name_plural": "weather data",
                "db_table": "weather_data",
                "ordering": ["date_time"],
                "indexes": [
                    models.Index(
                        fields=["city", "date_time"],
                        name="weather_dat_city_id_3719a7_idx",
                    )
                ],
                "unique_together": {("city", "date_time")},
            },
        ),
    ]
