# Generated by Django 5.2.6 on 2025-09-17 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="djangocity",
            unique_together={("name", "latitude", "longitude")},
        ),
    ]
